# open(r'RuleSet.list', 'r')
# open(r'DRuleSet.list', 'r')
# open(r'PRuleSet.list', 'r')

a = open(r'RuleSet.txt', 'w')
RuleSet = open(r'RuleSet.list', 'r')
a.write(RuleSet.read())
RuleSet.close()
a.close()
RuleSet = open(r'RuleSet.txt', 'r')
alllines = RuleSet.readlines()
RuleSet.close()
RuleSet = open(r'RuleSet.txt', 'w')
for eachline in alllines:
    a = eachline.strip() + ',REJECT\n'
    RuleSet.writelines(a)
RuleSet.close()

a = open(r'DRuleSet.txt', 'w')
DRuleSet = open(r'DRuleSet.list', 'r')
a.write(DRuleSet.read())
DRuleSet.close()
a.close()
DRuleSet = open(r'DRuleSet.txt', 'r')
alllines = DRuleSet.readlines()
DRuleSet.close()
DRuleSet = open(r'DRuleSet.txt', 'w')
for eachline in alllines:
    a = eachline.strip() + ',DIRECT\n'
    DRuleSet.writelines(a)
DRuleSet.close()

a = open(r'PRuleSet.txt', 'w')
PRuleSet = open(r'PRuleSet.list', 'r')
a.write(PRuleSet.read())
PRuleSet.close()
a.close()
PRuleSet = open(r'PRuleSet.txt', 'r')
alllines = PRuleSet.readlines()
PRuleSet.close()
PRuleSet = open(r'PRuleSet.txt', 'w')
for eachline in alllines:
    a = eachline.strip() + ',PROXY\n'
    PRuleSet.writelines(a)
PRuleSet.close()

All = open(r'custom.conf', 'w')
RuleSet = open(r'RuleSet.txt', 'r')
DRuleSet = open(r'DRuleSet.txt', 'r')
PRuleSet = open(r'PRuleSet.txt', 'r')
title = open(r'title.txt', 'r')
tail = open(r'tail.txt', 'r')

All.write(title.read())
All.write(PRuleSet.read())
All.write(DRuleSet.read())
All.write(RuleSet.read())
All.write(tail.read())
All.close()
RuleSet.close()
DRuleSet.close()
PRuleSet.close()
title.close()
tail.close()
